common:
    system : "PbPb"
    energy : 5.36 #center-of-mass energy in TeV
    particle : "pi0" 
    period : "LHC23zz"
    do_ptspectrum: True
    pt_bin: [1,10] #in GeV for LKB
    fit_sig: ["cb"]
    fit_bkg: ["pol1"]
    fit_min: [0.04, 0.06]
    fit_max: [0.24, 0.22]
    integral_sigma_min: [-3.0]
    integral_sigma_max: [+3.0]
data:
    subsystems: 
        - name: "PCMPCM"
          cutnames:
          - "analysis_analysis"
          - "qc_qc"
          - "qc_TPConly_qc_TPConly"
          - "qc_ITSTPC_qc_ITSTPC"
mc:
    cutnames:
    - "cutname0_mc"
    - "cutname1_mc"

