common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    particle : "eta" 
    period : "LHC22q"
    do_ptspectrum: True
    #pt_bin: [0.8, 1.2, 1.6, 2.0, 3,4,6,8,10] #in GeV
    #pt_bin: [1.0, 1.4, 1.8, 2.2, 2.6, 3,4,6,8,10] #in GeV
    pt_bin: [1.0, 2,3,4,6,8,10] #in GeV
    fit_sig: ["cb"]
    fit_bkg: ["pol1", "pol2"]
    fit_min: [0.35, 0.40]
    fit_max: [0.70, 0.75]
    integral_sigma_min: [-3.0]
    integral_sigma_max: [+3.0]
data:
    subsystems: 
        - name: "PCMPCM"
          cutnames:
          - "analysis_analysis"
          - "qc_qc"
#        - name: "PHOSPHOS"
#          cutnames:
#          - "test03_test03"
#          - "test05_test05"
#        - name: "EMCEMC"
#          cutnames:
#          - "standard_standard"
#        - name: "PCMPHOS"
#          cutnames:
#          - "analysis_test03"
#          - "analysis_wo_mee_test03"
#          - "qc_test03"
#          - "analysis_test05"
#          - "analysis_wo_mee_test05"
#          - "qc_test05"
#        - name: "PCMEMC"
#          cutnames:
#          - "analysis_standard"
#          - "analysis_wo_mee_standard"
#          - "qc_standard"
mc:
    cutnames:
    - "cutname0_mc"
    - "cutname1_mc"

