common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    period : "LHC22q"
    do_ptspectrum: True
    ptee_bin: [0.4,0.5,0.6,0.7,0.8, 0.9,1,1.2, 1.4, 1.6, 1.8,2,2.5,3,3.5,4,4.5,5,6,8,10] #in GeV
data:
    cutnames:
    - "cutname0_data"
    - "cutname1_data"
mc:
    cutnames:
    - "cutname0_mc"
    - "cutname1_mc"

