common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    particle : "pi0" 
    period : "LHC24b1"
    do_ptspectrum: True
    pt_bin: [0.2,0.3,0.4,0.5,0.6,0.7,0.8, 0.9, 1,1.2, 1.4, 1.6, 1.8,2,2.5,3,4,6] #in GeV
    fit_sig: ["cb"]
    fit_bkg: ["pol1"]
    fit_min: [0.04, 0.06]
    fit_max: [0.24, 0.22]
    integral_sigma_min: [-3.0]
    integral_sigma_max: [+3.0]
data:
    subsystems: 
        - name: "PCMDalitzEE"
          cutnames:
          - "qc_mee0_60_minpt100_maxeta09_tpconly_lowB"
mc:
    subsystems: 
        - name: "PCMDalitzEE"
          cutnames:
          - "qc_mee0_60_minpt100_maxeta09_tpconly_lowB"
