common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    particle : "photon" 
    period : "LHC23d1k"
    do_ptspectrum: True
    pt_bin: [0.05, 0.1,0.15, 0.2,0.3,0.4,0.5,0.6,0.7,0.8, 0.9,1,1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8,1.9, 2,2.2,2.4, 2.6, 2.8, 3,3.5,4,4.5,5,6,7,8,9,10] #in GeV
data:
    subsystems: 
        - name: "PCM"
          cutnames:
          - "qc"
          - "qc_ITSTPC"
          - "qc_ITSonly"
mc:
    subsystems: 
        - name: "PCM"
          cutnames:
          - "qc"
          - "qc_ITSTPC"
          - "qc_ITSonly"
