common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    meson : "pi0" 
    period : "LHC22q"
    do_ptspectrum: True
    pt_bin: [1.0, 10.0] #in GeV
    fit_sig: ["cb"]
    fit_bkg: ["pol1"]
    fit_min: [0.06]
    fit_max: [0.22]
    integral_sigma_min: [-3.0]
    integral_sigma_max: [+3.0]
data:
    subsystems: 
        - name: "PCMPCM"
          cutnames:
          - "analysis_analysis"
          - "analysis_wo_mee_analysis_wo_mee"
          - "qc_qc"
          - "nocut_nocut"
#        - name: "PHOSPHOS"
#          cutnames:
#          - "test03_test03"
#          - "test05_test05"
#        - name: "PCMPHOS"
#          cutnames:
#          - "analysis_test03"
#          - "analysis_wo_mee_test03"
#          - "qc_test03"
#          - "analysis_test05"
#          - "analysis_wo_mee_test05"
#          - "qc_test05"
mc:
    cutnames:
    - "cutname0_mc"
    - "cutname1_mc"
