common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    particle : "pi0" 
    period : "LHC22m"
    do_ptspectrum: True
    #pt_bin: [0.4,0.5,0.6,0.7,0.8, 0.9,1,1.2, 1.4, 1.6, 1.8,2,2.2,2.4,2.6,2.8,3,3.5,4,5,6,7,8,10,12,16] #in GeV
    pt_bin: [0.6,0.7,0.8, 0.9,1,1.2, 1.4, 1.6, 1.8,2,2.2,2.4,2.6,2.8,3,3.5,4,5,6,7,8,10,16] #in GeV
    fit_sig: ["cb"]
    fit_bkg: ["pol1"]
    fit_min: [0.04, 0.06]
    fit_max: [0.24, 0.22]
    integral_sigma_min: [-3.0]
    integral_sigma_max: [+3.0]
data:
    subsystems: 
        - name: "PCMPCM"
          cutnames:
          - "analysis_analysis"
          - "qc_qc"
          - "qc_ITSTPC_qc_ITSTPC"
          - "qc_TPConly_qc_TPConly"
          - "qc_ITSonly_qc_ITSonly"
#        - name: "PHOSPHOS"
#          cutnames:
#          - "test03_test03"
#          - "test05_test05"
#        - name: "EMCEMC"
#          cutnames:
#          - "standard_standard"
#        - name: "PCMPHOS"
#          cutnames:
#          - "analysis_test03"
#          - "qc_test03"
#          - "analysis_test05"
#          - "qc_test05"
#        - name: "PCMEMC"
#          cutnames:
#          - "analysis_standard"
#          - "qc_standard"
mc:
    cutnames:
    - "cutname0_mc"
    - "cutname1_mc"

