common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    particle : "pi0" 
    period : "LHC22m"
    do_ptspectrum: True
    #pt_bin: [0.4, 1.0, 2.0, 5.0] #in GeV
    #pt_bin: [1.0, 5.0] #in GeV
    pt_bin: [0.8, 5.0] #in GeV
    fit_sig: ["cb"]
    fit_bkg: ["pol1", "pol2"]
    fit_min: [0.04, 0.06]
    fit_max: [0.24, 0.22]
    integral_sigma_min: [-3.0]
    integral_sigma_max: [+3.0]
data:
    subsystems: 
        - name: "PCMPCM"
          cutnames:
          - "analysis_analysis"
          - "qc_qc"
#        - name: "PHOSPHOS"
#          cutnames:
#          - "test03_test03"
#          - "test05_test05"
#        - name: "PCMPHOS"
#          cutnames:
#          - "analysis_test03"
#          - "analysis_wo_mee_test03"
#          - "qc_test03"
#          - "analysis_test05"
#          - "analysis_wo_mee_test05"
#          - "qc_test05"
#        - name: "PCMEMC"
#          cutnames:
#          - "analysis_standard"
#          - "analysis_wo_mee_standard"
#          - "qc_standard"
#          - "nocut_standard"
mc:
    cutnames:
    - "cutname0_mc"
    - "cutname1_mc"
