common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    particle : "pi0" 
    period : "LHC22f"
    do_ptspectrum: True
    pt_bin: [0.6,0.8,1.0,1.5, 2.0,4]
    fit_sig: ["cb"]
    fit_bkg: ["pol1"]
    fit_min: [0.04]
    fit_max: [0.24]
    integral_sigma_min: [-3.0]
    integral_sigma_max: [+3.0]
data:
    subsystems: 
        - name: "PCMPCM"
          cutnames:
          - "analysis_analysis"
          - "analysis_wo_mee_analysis_wo_mee"
          - "qc_qc"
        - name: "PHOSPHOS"
          cutnames:
          - "test03_test03"
          - "test05_test05"
        - name: "EMCEMC"
          cutnames:
          - "standard_standard"
        - name: "PCMPHOS"
          cutnames:
          - "analysis_test03"
          - "analysis_wo_mee_test03"
          - "qc_test03"
          - "analysis_test05"
          - "analysis_wo_mee_test05"
          - "qc_test05"
        - name: "PCMEMC"
          cutnames:
          - "analysis_standard"
          - "analysis_wo_mee_standard"
          - "qc_standard"
mc:
    cutnames:
    - "cutname0_mc"
    - "cutname1_mc"

