common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    particle : "photon" 
    period : "LHC23d10"
    do_ptspectrum: True
    pt_bin: [0.2,0.3,0.4,0.5,0.6,0.7,0.8, 0.9,1,1.2, 1.4, 1.5, 1.6, 1.8,2,2.5,3,3.5,4,4.5,5,6,7,8,9,10] #in GeV
data:
    subsystems: 
        - name: "PCM"
          cutnames:
          - "analysis"
          - "analysis_wo_mee"
          - "qc"
mc:
    subsystems: 
        - name: "PCM"
          cutnames:
          - "analysis"
          - "analysis_wo_mee"
          - "qc"
